export const USER_INFO = '@App:user'
export const AUTH_TOKEN = '@App:token'
export const FIREBASE_TOKEN = '@App:fbtoken'
export const ACCOUNT_INFO = '@App:account'
export const APP_LOCALE = '@App:locale'
export const THEME = '@App:theme'
export const ORGANIZATION_INFO = '@App:organization'
export const CHANNEL_INFO = '@App:channel'
export const MAX_CARDS_SCROLLER_RESULTS = 10
export const DEFAULT_POLLING_INTERVAL = 30 * 1000
export const DEFAULT_LIMIT_QUERY = 20
