const {
  REACT_APP_FIREBASE_API_KEY = '',
  REACT_APP_FIREBASE_DOMAIN = '',
  REACT_APP_FIREBASE_DATABASE_URL = '',
  REACT_APP_FIREBASE_PROJECT = '',
  REACT_APP_FIREBASE_BUCKET = '',
  REACT_APP_FIREBASE_SENDER = '',
  REACT_APP_FIREBASE_APP_ID = '',
  REACT_APP_FIREBASE_MEASUREMENT_ID = '',
} = process.env

export const FIREBASE_CONFIG = Object.freeze({
  apiKey: REACT_APP_FIREBASE_API_KEY,
  authDomain: REACT_APP_FIREBASE_DOMAIN,
  databaseURL: REACT_APP_FIREBASE_DATABASE_URL,
  projectId: REACT_APP_FIREBASE_PROJECT,
  storageBucket: REACT_APP_FIREBASE_BUCKET,
  messagingSenderId: REACT_APP_FIREBASE_SENDER,
  appId: REACT_APP_FIREBASE_APP_ID,
  measurementId: REACT_APP_FIREBASE_MEASUREMENT_ID,
})
